# QuickPatch CLI workspace root. Forked from Shorebird (Apache/MIT, see LICENSE-*).
# Lists only the packages QuickPatch needs.
name: _
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - dex
  - jwt
  - scoped_deps
  - quickpatch_build_trace
  - quickpatch_cli
  - quickpatch_code_push_client
  - quickpatch_code_push_protocol

dev_dependencies:
  very_good_analysis: ^10.2.0
