import 'package:path/path.dart' as p;

/// {@template interpreter_build}
/// Pure construction of the toolchain invocations for QuickPatch's iOS
/// arbitrary-code-push (Dart interpreter / dynamic-modules) path.
///
/// The architecture, host-proven end-to-end against real `package:flutter`
/// (see the engine proofs 2-9 + the merge-loader):
///
///  * RELEASE base: the app's own `lib/` is compiled to a `dart2bytecode`
///    module (interpreted, patchable). The AOT image is compiled from a
///    generated BOOTSTRAPPER entrypoint that imports the framework (so the
///    framework stays AOT and is referenced — not bundled — by the module)
///    but NOT the app code (so the app libs are naturally excluded from AOT).
///    A generated `dynamic_interface.yaml` marks the framework surface
///    `callable`/`extendable`/`can-be-overridden` so it is retained in AOT and
///    kept open-dispatch (so AOT framework calls reach interpreted overrides).
///
///  * PATCH: the changed app `lib/` is compiled to a `dart2bytecode` module
///    UNPREFIXED (same library URIs as the base). The on-device same-URI
///    MERGE-LOADER resolves the patch's references to the base library (so
///    private selectors match live instances) and swaps the bytecode onto the
///    existing functions. Only the app's own functions are interpreted; the
///    framework stays native. Patches are tiny (~1-2 KB).
///
/// This class only BUILDS the argument vectors and source — running them is
/// the caller's job (mirroring how the CLI already shells out to gen_snapshot
/// / gen_kernel / aot_tools). Keeping it pure makes it unit-testable without
/// the engine toolchain or a device.
/// {@endtemplate}
abstract final class InterpreterBuild {
  /// The language experiment the current Flutter framework source requires
  /// (null-aware collection elements, used pervasively in package:flutter).
  static const experimentFlag = '--enable-experiment=null-aware-elements';

  /// Minimal `package:dynamic_modules` library source.
  ///
  /// The bootstrapper imports `package:dynamic_modules/dynamic_modules.dart`
  /// and calls [loadModuleFromBytes] / [loadModuleAsPatch]. Those are thin
  /// public wrappers over the `dart:_internal` dynamic-module natives
  /// (`loadDynamicModule` / `loadDynamicModulePatch`) — which are ALREADY baked
  /// into the engine's `platform_strong.dill`. The wrapper itself is a normal
  /// package and is NOT in the platform dill nor in any app's package_config,
  /// so gen_kernel cannot resolve it.
  ///
  /// Rather than vending a file in the engine bundle (which would force an
  /// engine republish per version), the CLI generates this ~4-line wrapper on
  /// the fly and points a package_config entry at it — exactly what the
  /// host/device proofs did by hand. No engine change is required because the
  /// natives it re-exports are part of the SDK platform dill.
  static const dynamicModulesLibrarySource = '''
// AUTO-GENERATED by QuickPatch — re-exports the dart:_internal dynamic-module
// natives (already present in the engine platform dill) as the public API the
// bootstrapper imports. Do not edit.
import 'dart:typed_data' show Uint8List;
import 'dart:_internal' as internal;

Future<Object?> loadModuleFromBytes(Uint8List bytes) =>
    internal.loadDynamicModule(bytes: bytes);

Future<Object?> loadModuleFromUri(Uri uri) =>
    internal.loadDynamicModule(uri: uri);

int loadModuleAsPatch(Uint8List bytes, String prefix) =>
    internal.loadDynamicModulePatch(bytes, prefix);
''';

  /// Generates the AOT bootstrapper `main()` source.
  ///
  /// It imports [frameworkImports] (so the framework is pulled into the AOT
  /// image and retained/open-dispatched by the generated interface) plus
  /// `package:dynamic_modules`, and loads the app bytecode module — whose
  /// entry-point IS the app's real `main()` (which calls `runApp`).
  ///
  /// The host/device split is isolated in `_qpAppModuleBytes`:
  ///  * [mode] == `'argv'`  — read a file path from `argv[0]` (host proofs);
  ///  * [mode] == `'asset'` — supplied by the engine load hook on device;
  ///  * [mode] == `'ota'`   — the PRODUCTION device variant: loads the app
  ///    bytecode module from the bundled asset [appModuleAssetKey], then after
  ///    the first frame downloads the latest `.bytecode` patch over HTTPS from
  ///    [otaPatchUrl] and applies it live via [loadModuleAsPatch] +
  ///    `reassembleApplication()`. This is the over-the-air code-push variant
  ///    proven on a physical iPhone (2026-05-30).
  ///
  /// When [applyPatch] is true (argv/asset modes) the bootstrapper, after
  /// loading the base app module, applies a staged patch via [loadModuleAsPatch]
  /// — the same-URI merge-loader swaps the changed functions onto the live app.
  static String generateBootstrapperMain({
    List<String> frameworkImports = const ['package:flutter/material.dart'],
    String mode = 'asset',
    String assetKey = 'assets/app.qpmod',
    bool applyPatch = true,
    String? otaPatchUrl,
    String appModuleAssetKey = 'assets/app.qpmod',
    Duration otaDelay = const Duration(seconds: 2),
    String? serverBaseUrl,
    String? appId,
    String? releaseVersion,
    String channel = 'stable',
    String? publicKeyBase64,
    List<String> rotationPublicKeysBase64 = const [],
    bool appUsesCodePush = false,
    bool autoUpdate = true,
    List<String> extraImports = const [],
  }) {
    if (mode == 'ota') {
      assert(otaPatchUrl != null, 'ota mode requires otaPatchUrl');
      return _otaBootstrapper(
        frameworkImports: frameworkImports,
        otaPatchUrl: otaPatchUrl!,
        appModuleAssetKey: appModuleAssetKey,
        otaDelaySeconds: otaDelay.inSeconds,
      );
    }
    if (mode == 'server') {
      assert(
        serverBaseUrl != null && appId != null && releaseVersion != null,
        'server mode requires serverBaseUrl, appId, releaseVersion',
      );
      return _serverBootstrapper(
        frameworkImports: frameworkImports,
        baseUrl: serverBaseUrl!,
        appId: appId!,
        releaseVersion: releaseVersion!,
        channel: channel,
        appModuleAssetKey: appModuleAssetKey,
        otaDelaySeconds: otaDelay.inSeconds,
        publicKeyBase64: publicKeyBase64 ?? '',
        rotationPublicKeysBase64: rotationPublicKeysBase64,
        appUsesCodePush: appUsesCodePush,
        autoUpdate: autoUpdate,
      );
    }
    assert(mode == 'argv' || mode == 'asset', 'mode must be argv|asset|ota');
    final b = StringBuffer()
      ..writeln('// AUTO-GENERATED QuickPatch bootstrapper — do not edit.')
      ..writeln("import 'dart:typed_data';");
    if (mode == 'argv') b.writeln("import 'dart:io';");
    for (final imp in frameworkImports) {
      b.writeln("import '$imp';");
    }
    // Extra libraries to pull into this bootstrapper's kernel. Used by the
    // PATCHER so its import-dill (= the patch module's external-library set)
    // covers the packages the RELEASE's server-mode bootstrapper baked into
    // the base (signature verification + code-push). Without them the patch
    // module bundles its own copies of libraries the base already holds and
    // fails to load on device ("library ... is already loaded").
    var extraIndex = 0;
    for (final imp in extraImports) {
      b.writeln("import '$imp' as qpx${extraIndex++}; // ignore: unused_import");
    }
    b
      ..writeln("import 'package:dynamic_modules/dynamic_modules.dart';")
      ..writeln()
      ..writeln('Future<void> main(List<String> args) async {')
      ..writeln('  await loadModuleFromBytes(await _qpAppModuleBytes(args));');
    if (applyPatch) {
      b
        ..writeln('  final patch = await _qpPatchBytes(args);')
        ..writeln('  if (patch != null) {')
        ..writeln('    // Same-URI merge-loader: swaps changed functions onto')
        ..writeln('    // the live app. The second arg (prefix) is ignored.')
        ..writeln("    loadModuleAsPatch(patch, '');")
        ..writeln('  }');
    }
    b
      ..writeln('}')
      ..writeln()
      ..writeln('Future<Uint8List> _qpAppModuleBytes(List<String> args) async {');
    if (mode == 'argv') {
      b.writeln('  return Uint8List.fromList(File(args[0]).readAsBytesSync());');
    } else {
      b
        ..writeln('  // Device: module ships as asset "$assetKey"; the engine')
        ..writeln('  // load hook supplies the bytes.')
        ..writeln("  throw UnimplementedError('engine hook supplies bytes');");
    }
    b.writeln('}');
    if (applyPatch) {
      b
        ..writeln()
        ..writeln('Future<Uint8List?> _qpPatchBytes(List<String> args) async {');
      if (mode == 'argv') {
        b
          ..writeln('  if (args.length < 2) return null;')
          ..writeln('  return Uint8List.fromList(File(args[1]).readAsBytesSync());');
      } else {
        b
          ..writeln('  // Device: the patch download/cache infra stages the')
          ..writeln('  // .bytecode; the engine hook supplies it (null = none).')
          ..writeln('  return null;');
      }
      b.writeln('}');
    }
    return b.toString();
  }

  /// The production over-the-air bootstrapper (mode `'ota'`). Loads the bundled
  /// app bytecode module, then downloads + applies the latest patch over HTTPS.
  static String _otaBootstrapper({
    required List<String> frameworkImports,
    required String otaPatchUrl,
    required String appModuleAssetKey,
    required int otaDelaySeconds,
  }) {
    final b = StringBuffer()
      ..writeln('// AUTO-GENERATED QuickPatch OTA bootstrapper — do not edit.')
      ..writeln("import 'dart:io';")
      ..writeln("import 'dart:typed_data';");
    for (final imp in frameworkImports) {
      b.writeln("import '$imp';");
    }
    b
      ..writeln("import 'package:flutter/services.dart' show rootBundle;")
      ..writeln("import 'package:dynamic_modules/dynamic_modules.dart';")
      ..writeln()
      ..writeln("const _otaPatchUrl = '$otaPatchUrl';")
      ..writeln()
      ..writeln('Future<void> main() async {')
      ..writeln('  WidgetsFlutterBinding.ensureInitialized();')
      ..writeln("  final appBytes =")
      ..writeln("      (await rootBundle.load('$appModuleAssetKey')).buffer.asUint8List();")
      ..writeln('  await loadModuleFromBytes(appBytes); // app main() -> runApp')
      ..writeln('  WidgetsBinding.instance.addPostFrameCallback((_) async {')
      ..writeln('    await Future<void>.delayed(')
      ..writeln('        const Duration(seconds: $otaDelaySeconds));')
      ..writeln('    try {')
      ..writeln('      final patch = await _qpDownloadPatch();')
      ..writeln('      if (patch == null || patch.isEmpty) return;')
      ..writeln("      loadModuleAsPatch(patch, '');")
      ..writeln('      WidgetsBinding.instance.reassembleApplication();')
      ..writeln('    } on Object catch (e) {')
      ..writeln("      debugPrint('QUICKPATCH: OTA skipped (\$e)');")
      ..writeln('    }')
      ..writeln('  });')
      ..writeln('}')
      ..writeln()
      ..writeln('Future<Uint8List?> _qpDownloadPatch() async {')
      ..writeln('  final client = HttpClient();')
      ..writeln('  try {')
      ..writeln('    final res = await (await client.getUrl(Uri.parse(_otaPatchUrl))).close();')
      ..writeln('    if (res.statusCode != 200) return null;')
      ..writeln('    final bb = BytesBuilder(copy: false);')
      ..writeln('    await for (final c in res) {')
      ..writeln('      bb.add(c);')
      ..writeln('    }')
      ..writeln('    return bb.takeBytes();')
      ..writeln('  } finally {')
      ..writeln('    client.close(force: true);')
      ..writeln('  }')
      ..writeln('}');
    return b.toString();
  }

  /// The production server-routed OTA bootstrapper (mode `'server'`).
  ///
  /// **Download-now / apply-on-next-launch** semantics (NOT a live hot-swap):
  ///  * BOOT — after loading the bundled base module, it applies any previously
  ///    STAGED patch from disk (re-verified) via [loadModuleAsPatch] *before the
  ///    first frame*, so the very first paint is already patched (no flash of
  ///    the old UI, no `reassembleApplication()` morph).
  ///  * BACKGROUND — after the first frame it queries the patch-check API
  ///    ([baseUrl]/api/v1/patches/check) for the current release/channel; a
  ///    newer, signature-verified patch is downloaded and STAGED to disk
  ///    (atomic temp+rename). It is never applied to the running session — it
  ///    takes effect on the next launch. A server rollback of the running patch
  ///    clears the stage so the next launch reverts to the base.
  ///
  /// Routed through the real QuickPatch channel (release / track / rollback)
  /// rather than a hardcoded CDN URL.
  static String _serverBootstrapper({
    required List<String> frameworkImports,
    required String baseUrl,
    required String appId,
    required String releaseVersion,
    required String channel,
    required String appModuleAssetKey,
    required int otaDelaySeconds,
    required String publicKeyBase64,
    List<String> rotationPublicKeysBase64 = const [],
    bool appUsesCodePush = false,
    bool autoUpdate = true,
  }) {
    final base = baseUrl.replaceAll(RegExp(r'/+$'), '');
    // The ordered set of keys the bootstrapper trusts to verify a patch:
    // primary key first, then any rotation keys. A patch is accepted if it
    // verifies against any one of them (see `_qpVerify`). Empty => unsigned.
    final trustedKeys = <String>[
      if (publicKeyBase64.isNotEmpty) publicKeyBase64,
      ...rotationPublicKeysBase64
          .map((k) => k.trim())
          .where((k) => k.isNotEmpty),
    ];
    final keysLiteral = trustedKeys.map((k) => "'$k'").join(', ');
    final b = StringBuffer()
      ..writeln('// AUTO-GENERATED QuickPatch server-OTA bootstrapper.')
      ..writeln("import 'dart:convert';")
      ..writeln("import 'dart:io';")
      ..writeln("import 'dart:math' show Random;")
      ..writeln("import 'dart:typed_data';");
    for (final imp in frameworkImports) {
      b.writeln("import '$imp';");
    }
    b
      ..writeln("import 'package:flutter/services.dart' show rootBundle;")
      ..writeln("import 'package:dynamic_modules/dynamic_modules.dart';")
      ..writeln("import 'package:asn1lib/asn1lib.dart' as asn1;")
      ..writeln("import 'package:crypto/crypto.dart' as crypto;")
      ..writeln("import 'package:pointycastle/pointycastle.dart' as pc;");
    // When the app depends on quickpatch_code_push, import + reference it here so
    // its FULL transitive surface — including the private dart:ffi/dart:isolate
    // runtime helpers (e.g. _loadAbiSpecificInt, Isolate.run) its native
    // bindings use — is reachable from this AOT bootstrapper's roots and thus
    // RETAINED in the base image. The interpreted app module ships its own copy
    // of quickpatch_code_push as bytecode and resolves those helpers against the
    // base; without this they get tree-shaken and the interpreter FATALs at
    // module load. @pragma('vm:entry-point') keeps the retainer even though
    // nothing calls it.
    if (appUsesCodePush) {
      b
        ..writeln(
          "import 'package:quickpatch_code_push/quickpatch_code_push.dart' as qpcp;")
        ..writeln()
        ..writeln("@pragma('vm:entry-point')")
        ..writeln('List<Object?> _qpRetainCodePush() {')
        ..writeln('  final u = qpcp.QuickPatchUpdater();')
        ..writeln('  return <Object?>[')
        ..writeln('    u.checkForUpdate, u.update, u.readCurrentPatch,')
        ..writeln('    u.readNextPatch, u.isAvailable,')
        ..writeln('  ];')
        ..writeln('}')
        ..writeln()
        // Route the quickpatch_code_push public API to the interpreter's
        // staged full-module OTA flow. The native binary-diff updater cannot
        // process bytecode-module patches (zstd-magic mismatch), so the
        // bootstrapper — which owns the staged-patch storage — services
        // check/update/patch-number calls itself. The app module resolves
        // quickpatch_code_push against THIS base copy, so the static slots
        // set here are the ones the app's QuickPatchUpdater sees.
        ..writeln('void _qpInstallCodePushHooks() {')
        ..writeln(
            '  qpcp.QuickPatchInterpreterOverrides.currentPatchNumber = () => _qpApplied;')
        ..writeln(
            '  qpcp.QuickPatchInterpreterOverrides.nextPatchNumber = _qpNextBootNumber;')
        ..writeln(
            '  qpcp.QuickPatchInterpreterOverrides.checkForDownloadableUpdate =')
        ..writeln('      _qpCheckDownloadable;')
        ..writeln(
            '  qpcp.QuickPatchInterpreterOverrides.update = _qpDownloadAndStage;')
        ..writeln('}');
    } else {
      b
        ..writeln()
        ..writeln('void _qpInstallCodePushHooks() {}');
    }
    b
      ..writeln()
      ..writeln("const _base = '$base';")
      ..writeln("const _appId = '$appId';")
      ..writeln("const _releaseVersion = '$releaseVersion';")
      ..writeln("const _channel = '$channel';")
      ..writeln('const _publicKeysB64 = <String>[$keysLiteral];')
      ..writeln("const _appModuleAssetKey = '$appModuleAssetKey';")
      ..writeln('const _otaDelaySeconds = $otaDelaySeconds;')
      ..writeln('const _autoUpdate = $autoUpdate;')
      ..writeln()
      // The static body uses only the consts above; emit it raw so the
      // generated code's own `$` interpolations stay literal.
      ..write(_serverBootstrapperBody);
    return b.toString();
  }

  /// The static portion of the server-OTA bootstrapper (everything after the
  /// generated `const _…` header). Emitted raw so the generated code's own
  /// `$…` interpolations are preserved verbatim; it depends only on the
  /// `_base`/`_appId`/`_releaseVersion`/`_channel`/`_publicKeysB64`/
  /// `_appModuleAssetKey`/`_otaDelaySeconds` consts the header defines.
  static const _serverBootstrapperBody = r'''
// Staged OTA: a downloaded patch is NEVER applied to the running session. It is
// STAGED to disk and applied at the NEXT launch, before the first frame — so the
// first paint is already patched (no flash of the old UI, no live reassemble).
// The patch number the running session booted from (0 = base). Global so the
// code-push hooks can report it.
int _qpApplied = 0;

// Set when the server rolled back the running patch: the stage is cleared and
// the next launch boots the base, so "next boot" reports 0 until then.
bool _qpRevertPending = false;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Route the code-push package's updater API (if the app uses it) to the
  // staged full-module flow below — installed before the app module runs so
  // its very first updater call already sees the hooks.
  _qpInstallCodePushHooks();

  // 1) BOOT-TIME LOAD (full-module replacement): a patch IS the
  //    whole changed app compiled to bytecode. If one is staged + re-verified,
  //    load and RUN it (its main() -> runApp) INSTEAD of the bundled base — so
  //    ANY code change takes effect, including brand-new classes/screens (which
  //    the old function-merge path could not add). The first frame is HELD
  //    (deferFirstFrame) so the first paint is already the patched app.
  //
  //    Self-heal: a staged patch that hard-crashes at load would otherwise brick
  //    every launch (the crash precedes the rollback check). A boot-failure
  //    counter (bumped before load, reset after the first frame renders) drops a
  //    staged patch that has crashed repeatedly, falling back to the base.
  WidgetsBinding.instance.deferFirstFrame();
  final pre = _qpReadStaged();
  if (pre != null && _qpBumpBootFailures() > 2) {
    _qpClearStaged();
    _qpResetBootFailures();
    debugPrint('QUICKPATCH: staged patch crashed repeatedly at boot; cleared');
  }
  try {
    final staged = _qpReadStaged();
    var loadedStaged = false;
    if (staged != null) {
      try {
        await loadModuleFromBytes(staged.bytes); // patched app main() -> runApp
        _qpApplied = staged.number;
        loadedStaged = true;
        debugPrint('QUICKPATCH: staged patch #${staged.number} loaded at boot');
      } on Object catch (e) {
        // A staged patch that fails to LOAD (not crash) would otherwise leave
        // the app blank forever: the failure renders an empty frame, which
        // resets the crash counter, so the bad stage is never dropped. Clear
        // it and fall back to the bundled base.
        debugPrint(
            'QUICKPATCH: staged patch #${staged.number} failed to load ($e); '
            'clearing stage and falling back to base');
        _qpClearStaged();
      }
    }
    if (!loadedStaged) {
      final appBytes =
          (await rootBundle.load(_appModuleAssetKey)).buffer.asUint8List();
      await loadModuleFromBytes(appBytes); // base app main() -> runApp
      debugPrint('QUICKPATCH: running base');
    }
  } on Object catch (e) {
    debugPrint('QUICKPATCH: boot-load skipped ($e)');
  } finally {
    WidgetsBinding.instance.allowFirstFrame();
  }

  // 2) BACKGROUND DOWNLOAD (after first frame): fetch a newer patch and STAGE
  //    it for the next launch. Never applied live. Skipped when auto_update is
  //    disabled in quickpatch.yaml — updates are then user-driven via the
  //    code-push package (checkForUpdate/update), which the hooks above
  //    service.
  WidgetsBinding.instance.addPostFrameCallback((_) async {
    // The patched app rendered its first frame — it's healthy, so clear the
    // boot-failure counter.
    _qpResetBootFailures();
    // A patched module reached its first frame == a successful install. Report
    // it once per applied patch, regardless of auto_update (that flag only
    // governs background OTA, not whether the running patch installed).
    if (_qpApplied > 0) {
      await _qpReportEvent('__patch_install__', _qpApplied, 'installed');
    }
    if (!_autoUpdate) {
      debugPrint('QUICKPATCH: auto_update disabled; skipping OTA check');
      return;
    }
    await Future<void>.delayed(const Duration(seconds: _otaDelaySeconds));
    try {
      debugPrint(
          'QUICKPATCH: OTA check (release=$_releaseVersion, have=#$_qpApplied)');
      final res = await _qpCheckServer(_qpApplied);
      if (res == null) {
        debugPrint('QUICKPATCH: OTA check unavailable');
        return;
      }
      // A server rollback of the patch we are running -> drop the stage so the
      // next launch reverts to the base.
      if (res.rolledBack.contains(_qpApplied) && _qpApplied != 0) {
        _qpClearStaged();
        _qpRevertPending = true;
        debugPrint('QUICKPATCH: patch #$_qpApplied rolled back; staged cleared');
        return;
      }
      final p = res.patch;
      if (p == null) {
        debugPrint('QUICKPATCH: no newer patch');
        return;
      }
      _qpWriteStaged(p);
      _qpRevertPending = false;
      debugPrint('QUICKPATCH: patch #${p.number} STAGED for next launch');
      await _qpReportEvent('__patch_download__', p.number, 'downloaded');
    } on Object catch (e) {
      debugPrint('QUICKPATCH: OTA error ($e)');
    }
  });
}

// ---- code-push hook implementations (staged full-module flow) ----

// The patch number that boots on the NEXT launch: the staged patch if any,
// the base (0) after a rollback, else whatever is running now.
int _qpNextBootNumber() {
  if (_qpRevertPending) return 0;
  return _qpReadStaged()?.number ?? _qpApplied;
}

// True when the server has a patch newer than what is running/staged.
// Check-only: does NOT download. Also observes a server rollback of the
// running patch (clears the stage so the next launch reverts to the base).
Future<bool> _qpCheckDownloadable() async {
  final have = _qpReadStaged()?.number ?? _qpApplied;
  final body = await _qpPostCheck(have);
  if (body == null) return false;
  final rolled = (body['rolled_back_patch_numbers'] as List?)
          ?.map((e) => (e as num).toInt())
          .toList() ??
      const <int>[];
  if (rolled.contains(_qpApplied) && _qpApplied != 0) {
    _qpClearStaged();
    _qpRevertPending = true;
    debugPrint('QUICKPATCH: patch #$_qpApplied rolled back; staged cleared');
  }
  if (body['patch_available'] != true) return false;
  final number =
      ((body['patch'] as Map<String, dynamic>?)?['number'] as num?)?.toInt() ??
          0;
  return number > have;
}

// Download + verify + stage the newest patch for the next launch (the
// user-consented "update now" path). Throws on failure so the caller can
// surface it.
Future<void> _qpDownloadAndStage() async {
  final res = await _qpCheckServer(_qpApplied);
  if (res == null) {
    throw StateError('patch check failed (network or server error)');
  }
  if (res.rolledBack.contains(_qpApplied) && _qpApplied != 0) {
    _qpClearStaged();
    _qpRevertPending = true;
    debugPrint('QUICKPATCH: patch #$_qpApplied rolled back; staged cleared');
    return;
  }
  final p = res.patch;
  if (p == null) return; // already up to date
  _qpWriteStaged(p);
  _qpRevertPending = false;
  debugPrint('QUICKPATCH: patch #${p.number} STAGED for next launch');
  await _qpReportEvent('__patch_download__', p.number, 'downloaded');
}

class _QpStaged {
  _QpStaged(this.bytes, this.number, this.hash, this.sig);
  final Uint8List bytes;
  final int number;
  final String? hash;
  final String? sig;
}

class _QpCheck {
  _QpCheck(this.patch, this.rolledBack);
  final _QpStaged? patch;
  final List<int> rolledBack;
}

// iOS sandbox: systemTemp = <container>/tmp, so its parent is the app
// container; we stage under Application Support (app-private).
Directory _qpStageDir() {
  final container = Directory.systemTemp.parent.path;
  return Directory(
      '$container/Library/Application Support/quickpatch/qp_stage');
}

// App-private data dir that survives `_qpClearStaged()` (which deletes only
// qp_stage). Holds the persistent client id and telemetry-dedupe state, so a
// staged-patch rollback never churns the device identity or re-counts events.
Directory _qpDataDir() {
  final container = Directory.systemTemp.parent.path;
  return Directory('$container/Library/Application Support/quickpatch');
}

// A stable per-install device id, generated once and reused. Keeps
// download/install telemetry counting real devices (not launches). Best-effort:
// on any IO error we fall back to a constant so a broken sandbox can't spam new
// ids (which would inflate counts).
String _qpClientId() {
  try {
    final f = File('${_qpDataDir().path}/client_id');
    if (f.existsSync()) {
      final v = f.readAsStringSync().trim();
      if (v.isNotEmpty) return v;
    }
    final r = Random.secure();
    final id = List<int>.generate(16, (_) => r.nextInt(256))
        .map((b) => b.toRadixString(16).padLeft(2, '0'))
        .join();
    f.parent.createSync(recursive: true);
    f.writeAsStringSync(id, flush: true);
    return id;
  } on Object {
    return 'ios-unknown';
  }
}

Map<String, dynamic> _qpReadReported() {
  try {
    final f = File('${_qpDataDir().path}/reported.json');
    if (f.existsSync()) {
      return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    }
  } on Object {
    // best-effort
  }
  return <String, dynamic>{};
}

// Report a patch lifecycle event to the dashboard. The native binary-diff
// updater emits download/install events on Android, but the iOS interpreter's
// staged-module flow lives entirely here and is invisible to it — so we report
// them ourselves. Fire-and-forget: never throws, never blocks the app.
// [dedupeKey] ('downloaded' | 'installed') makes each (event, patch) count at
// most once per install, since these are per-device counters, not per-launch.
Future<void> _qpReportEvent(String type, int patchNumber, String dedupeKey) async {
  if (patchNumber <= 0) return;
  try {
    final reported = _qpReadReported();
    if ((reported[dedupeKey] as num?)?.toInt() == patchNumber) return;
    final client = HttpClient();
    try {
      final req =
          await client.postUrl(Uri.parse('$_base/api/v1/patches/events'));
      req.headers.contentType = ContentType.json;
      req.write(jsonEncode({
        'event': {
          'app_id': _appId,
          'arch': 'aarch64',
          'client_id': _qpClientId(),
          'type': type,
          'patch_number': patchNumber,
          'platform': 'ios',
          'release_version': _releaseVersion,
          'timestamp': DateTime.now().millisecondsSinceEpoch ~/ 1000,
        }
      }));
      final res = await req.close();
      await res.drain<void>();
      if (res.statusCode != 200) return; // retry next launch
    } finally {
      client.close(force: true);
    }
    reported[dedupeKey] = patchNumber;
    final f = File('${_qpDataDir().path}/reported.json');
    f.parent.createSync(recursive: true);
    f.writeAsStringSync(jsonEncode(reported), flush: true);
  } on Object catch (e) {
    debugPrint('QUICKPATCH: event report failed ($e)');
  }
}

// Boot-failure counter (self-heal). Bumped before applying a staged patch and
// reset once the first frame renders; if a staged patch crashes at load it is
// dropped after a few failed boots so it can never permanently brick the app.
File _qpBootFailFile() => File('${_qpStageDir().path}/boot_fails');

int _qpBumpBootFailures() {
  try {
    final f = _qpBootFailFile();
    final n =
        (f.existsSync() ? int.tryParse(f.readAsStringSync().trim()) ?? 0 : 0) +
            1;
    f.parent.createSync(recursive: true);
    f.writeAsStringSync('$n', flush: true);
    return n;
  } on Object {
    return 0;
  }
}

void _qpResetBootFailures() {
  try {
    final f = _qpBootFailFile();
    if (f.existsSync()) f.deleteSync();
  } on Object {
    // best-effort
  }
}

// Read + re-verify the staged patch for THIS release. Returns null when there
// is none, it targets a different release, or it fails re-verification.
_QpStaged? _qpReadStaged() {
  final dir = _qpStageDir();
  final meta = File('${dir.path}/patch.json');
  final blob = File('${dir.path}/patch.qpmod');
  if (!meta.existsSync() || !blob.existsSync()) return null;
  final m = jsonDecode(meta.readAsStringSync()) as Map<String, dynamic>;
  if (m['release_version'] != _releaseVersion) {
    debugPrint(
        'QUICKPATCH: staged patch for ${m['release_version']} != $_releaseVersion; ignoring');
    return null;
  }
  final bytes = Uint8List.fromList(blob.readAsBytesSync());
  final hash = m['hash'] as String?;
  final sig = m['sig'] as String?;
  if (!_qpVerify(bytes, hash, sig)) {
    debugPrint('QUICKPATCH: staged patch failed re-verify; ignoring');
    return null;
  }
  return _QpStaged(bytes, (m['number'] as num?)?.toInt() ?? 0, hash, sig);
}

// Atomically stage a verified patch: write temp files then rename over the
// live names so a crash mid-write can never leave a half-written patch that
// boots.
void _qpWriteStaged(_QpStaged p) {
  final dir = _qpStageDir();
  if (!dir.existsSync()) dir.createSync(recursive: true);
  File('${dir.path}/patch.qpmod.tmp').writeAsBytesSync(p.bytes, flush: true);
  File('${dir.path}/patch.json.tmp').writeAsStringSync(
    jsonEncode({
      'number': p.number,
      'release_version': _releaseVersion,
      'hash': p.hash,
      'sig': p.sig,
    }),
    flush: true,
  );
  File('${dir.path}/patch.qpmod.tmp').renameSync('${dir.path}/patch.qpmod');
  File('${dir.path}/patch.json.tmp').renameSync('${dir.path}/patch.json');
  // A freshly-staged patch starts with a clean self-heal counter, so a prior
  // patch's boot failures don't count against it.
  _qpResetBootFailures();
}

void _qpClearStaged() {
  final dir = _qpStageDir();
  if (dir.existsSync()) dir.deleteSync(recursive: true);
}

// POST the patch-check API and return the parsed response body. Returns null
// only on a transport/HTTP failure (so callers leave the current stage
// untouched). Check-only: never downloads.
Future<Map<String, dynamic>?> _qpPostCheck(int currentPatchNumber) async {
  final client = HttpClient();
  try {
    final checkReq =
        await client.postUrl(Uri.parse('$_base/api/v1/patches/check'));
    checkReq.headers.contentType = ContentType.json;
    checkReq.write(jsonEncode({
      'app_id': _appId,
      'channel': _channel,
      'release_version': _releaseVersion,
      'platform': 'ios',
      'arch': 'aarch64',
      'current_patch_number': currentPatchNumber,
    }));
    final checkRes = await checkReq.close();
    if (checkRes.statusCode != 200) return null;
    return jsonDecode(await checkRes.transform(utf8.decoder).join())
        as Map<String, dynamic>;
  } on Object {
    return null;
  } finally {
    client.close(force: true);
  }
}

// Query the patch-check API. Downloads + verifies a newer patch (returned in
// `patch`) and surfaces any `rolled_back_patch_numbers`. Returns null only on
// a transport/HTTP failure (so the caller leaves the current stage untouched).
Future<_QpCheck?> _qpCheckServer(int currentPatchNumber) async {
  final body = await _qpPostCheck(currentPatchNumber);
  if (body == null) return null;
  final rolled = (body['rolled_back_patch_numbers'] as List?)
          ?.map((e) => (e as num).toInt())
          .toList() ??
      const <int>[];
  if (body['patch_available'] != true) {
    return _QpCheck(null, rolled);
  }
  final patch = body['patch'] as Map<String, dynamic>;
  final number = (patch['number'] as num?)?.toInt() ?? 0;
  final url = patch['download_url'] as String;
  final hash = patch['hash'] as String?;
  final sig = patch['hash_signature'] as String?;
  final client = HttpClient();
  try {
    final dlRes = await (await client.getUrl(Uri.parse(url))).close();
    if (dlRes.statusCode != 200) return _QpCheck(null, rolled);
    final bb = BytesBuilder(copy: false);
    await for (final c in dlRes) {
      bb.add(c);
    }
    final bytes = bb.takeBytes();
    // SECURITY: only stage a patch whose signature verifies against the public
    // key embedded at release time.
    if (!_qpVerify(bytes, hash, sig)) {
      debugPrint('QUICKPATCH: downloaded patch verification FAILED — rejected');
      return _QpCheck(null, rolled);
    }
    return _QpCheck(_QpStaged(bytes, number, hash, sig), rolled);
  } finally {
    client.close(force: true);
  }
}

// Verify integrity (sha256) + authenticity (RSA-SHA256 over the hex hash)
// against ANY of the embedded trusted public keys. An empty key list => unsigned
// release (no key provided at release); signed patches require a valid signature.
// Accepting any one of several keys is what enables signing-key rotation: a build
// trusts the primary key plus rotation keys, so a patch signed by a rotated key
// verifies alongside one signed by the prior key. A valid-but-wrong key is
// skipped (its verify returns false / throws), not accepted.
bool _qpVerify(Uint8List bytes, String? hashHex, String? sigB64) {
  final keys = _publicKeysB64.where((k) => k.isNotEmpty).toList();
  if (keys.isEmpty) return true; // unsigned release
  if (hashHex == null || sigB64 == null) return false;
  if (crypto.sha256.convert(bytes).toString() != hashHex) return false;
  final msg = Uint8List.fromList(utf8.encode(hashHex));
  final sig = pc.RSASignature(base64.decode(sigB64));
  for (final key in keys) {
    try {
      final seq =
          asn1.ASN1Parser(base64.decode(key)).nextObject() as asn1.ASN1Sequence;
      final mod = (seq.elements[0] as asn1.ASN1Integer).valueAsBigInteger;
      final exp = (seq.elements[1] as asn1.ASN1Integer).valueAsBigInteger;
      final v = pc.Signer('SHA-256/RSA')
        ..init(false,
            pc.PublicKeyParameter<pc.RSAPublicKey>(pc.RSAPublicKey(mod, exp)));
      if (v.verifySignature(msg, sig)) return true;
    } on Object {
      // Undecodable/mismatched key — try the next trusted key.
    }
  }
  return false;
}
''';

  /// Arguments for compiling [entry] to the bootstrapper AOT kernel (or, with
  /// [noLinkPlatform], the `--import-dill` base used by [dart2bytecodeArgs]).
  ///
  /// [dynamicInterfacePath], when provided, flows the generated framework
  /// interface into the compile (keeps the framework surface retained +
  /// open-dispatch). The result is passed to the genKernel snapshot via
  /// `dartaotruntime`.
  static List<String> genKernelArgs({
    required String genKernelSnapshot,
    required String platformDill,
    required String packageConfig,
    required String entry,
    required String output,
    String? dynamicInterfacePath,
    bool noLinkPlatform = false,
    bool product = false,
    bool aot = false,
  }) {
    return [
      genKernelSnapshot,
      if (aot) '--aot',
      '--target', 'flutter',
      '--platform', platformDill,
      '--packages', packageConfig,
      '-Ddart.vm.product=$product',
      if (noLinkPlatform) '--no-link-platform',
      if (dynamicInterfacePath != null) ...[
        '--dynamic-interface',
        dynamicInterfacePath,
      ],
      experimentFlag,
      '--output', output,
      entry,
    ];
  }

  /// Arguments for compiling [entry] (the changed app for a patch, or the whole
  /// app `lib/` for the release base module) to a `dart2bytecode` module.
  ///
  /// [importDill] is the base bootstrapper kernel (supplies the framework so
  /// the module REFERENCES it). The patch is intentionally UNPREFIXED so the
  /// on-device merge-loader resolves references to the base library.
  static List<String> dart2bytecodeArgs({
    required String dart2bytecodeSnapshot,
    required String platformDill,
    required String packageConfig,
    required String importDill,
    required String entry,
    required String output,
    bool product = false,
  }) {
    return [
      dart2bytecodeSnapshot,
      '--target', 'flutter',
      '--platform', platformDill,
      '--packages', packageConfig,
      '-Ddart.vm.product=$product',
      '--import-dill', importDill,
      experimentFlag,
      '--output', output,
      entry,
    ];
  }

  /// Arguments for the framework dynamic-interface generator (run with a Dart
  /// that can resolve `package:kernel`). It walks [inputDill] and emits the
  /// framework/SDK surface, excluding [appPackages] (the app's own libs are
  /// bytecode-from-start and need no marking).
  static List<String> genInterfaceArgs({
    required String generatorScript,
    required String inputDill,
    required String outputYaml,
    required List<String> appPackages,
  }) {
    return [
      generatorScript,
      inputDill,
      outputYaml,
      for (final pkg in appPackages) '--app-package=$pkg',
    ];
  }

  /// Standard on-disk name of the app bytecode module bundled with a release.
  static String appModuleAssetName = 'app.qpmod';

  /// Path of the app bytecode module within [buildDir].
  static String appModulePath(String buildDir) =>
      p.join(buildDir, appModuleAssetName);
}
